modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL="https://github.com/user-12892/furniturecraft/issues"
[[mods]]
modId="furniturecraft"
version="0.0.11-1.19"
displayName="Furniture Craft"
logoFile="furniturecraft_icon.png"
authors="User12892"

description='''
Furniturecraft!
'''
# Forge
[[dependencies.furniturecraft]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
# Minecraft
[[dependencies.furniturecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
# Catalogue
[[dependencies.furniturecraft]]
modId="catalogue"
mandatory=false
versionRange="[1.6.2,)"
ordering="NONE"
side="CLIENT"
# Catalogue Icon
[modproperties.furniturecraft]
catalogueItemIcon="minecraft:paper"
