modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL="https://github.com/user-12892/furniturecraft/issues" #optional
[[mods]]
modId="furniturecraft"
version="0.0.8-1.19"
displayName="Furniture Craft"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="furniturecraft_icon.png"
authors="User12892"

description='''
Furniturecraft!
'''
# Forge
[[dependencies.furniturecraft]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
# Minecraft
[[dependencies.furniturecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
# Catalogue
[[dependencies.furniturecraft]]
modId="catalogue"
mandatory=false
versionRange="[1.6.2,)"
ordering="NONE"
side="CLIENT"
# Catalogue Icon
[modproperties.furniturecraft]
catalogueImageIcon="furniturcraft_icon_catalogue.png"
